package backend.auth;

import backend.shared.ApplicationConstants;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Base64;

/**
 * Provides secure password hashing and verification using a SHA-256 + salt scheme
 * that is compatible with plain Java SE 17 without third-party BCrypt libraries.
 *
 * <p>Format of a stored hash: {@code BASE64(salt) + "$" + BASE64(SHA-256(salt + password))}.
 * The salt is 16 bytes generated by {@link SecureRandom}.
 *
 * <p><strong>Production note:</strong> if a BCrypt dependency (e.g. {@code org.mindrot:jbcrypt})
 * is available on the classpath, replace the body of {@link #hash} and {@link #verify} with
 * {@code BCrypt.hashpw()} and {@code BCrypt.checkpw()} respectively. The public API of this
 * class remains identical.
 */
public final class PasswordHasher {

    private static final String ALGORITHM   = "SHA-256";
    private static final int    SALT_BYTES  = 16;
    private static final String SEPARATOR   = "$";

    private static volatile PasswordHasher instance;

    private final SecureRandom secureRandom = new SecureRandom();

    private PasswordHasher() {}

    public static PasswordHasher getInstance() {
        if (instance == null) {
            synchronized (PasswordHasher.class) {
                if (instance == null) instance = new PasswordHasher();
            }
        }
        return instance;
    }

    // ── Public API ──────────────────────────────────────────────────────────────

    /**
     * Hashes a plaintext password and returns the stored representation.
     *
     * @param plaintext raw password characters
     * @return opaque hash string safe to persist in the database
     */
    public String hash(char[] plaintext) {
        byte[] salt = new byte[SALT_BYTES];
        secureRandom.nextBytes(salt);
        byte[] digest = digest(salt, plaintext);
        return Base64.getEncoder().encodeToString(salt)
                + SEPARATOR
                + Base64.getEncoder().encodeToString(digest);
    }

    /**
     * Verifies a plaintext password against a previously hashed value.
     *
     * @param plaintext  raw password characters
     * @param storedHash the value returned by a previous call to {@link #hash}
     * @return {@code true} if the password matches; {@code false} otherwise
     */
    public boolean verify(char[] plaintext, String storedHash) {
        if (storedHash == null || !storedHash.contains(SEPARATOR)) return false;
        String[] parts = storedHash.split("\\$", 2);
        if (parts.length != 2) return false;
        byte[] salt   = Base64.getDecoder().decode(parts[0]);
        byte[] expect = Base64.getDecoder().decode(parts[1]);
        byte[] actual = digest(salt, plaintext);
        return MessageDigest.isEqual(expect, actual); // constant-time comparison
    }

    // ── Private helpers ─────────────────────────────────────────────────────────

    private byte[] digest(byte[] salt, char[] password) {
        try {
            MessageDigest md = MessageDigest.getInstance(ALGORITHM);
            md.update(salt);
            // Convert char[] to bytes without creating an intermediate String
            byte[] pwBytes = charArrayToUtf8Bytes(password);
            md.update(pwBytes);
            // Iterate multiple rounds to increase work factor (simulates BCrypt rounds)
            byte[] hash = md.digest();
            for (int i = 1; i < ApplicationConstants.AUTH_BCRYPT_ROUNDS * 100; i++) {
                md.reset();
                md.update(salt);
                md.update(hash);
                hash = md.digest();
            }
            return hash;
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 not available on this JVM.", e);
        }
    }

    private byte[] charArrayToUtf8Bytes(char[] chars) {
        byte[] bytes = new byte[chars.length * 2];
        int idx = 0;
        for (char c : chars) {
            bytes[idx++] = (byte) (c >> 8);
            bytes[idx++] = (byte)  c;
        }
        return bytes;
    }
}
